### ISSUE TITLE
Pausing the game, unfocusing and focusing the window, and unpausing makes the music disappear

### ISSUE THREAD

**Issue by RunninPigeon** [alesan99/mari0_ae#606] opened 2024-05-26 06:14 UTC

**Comment by WilliamFr0g** [comment] 2024-05-26 23:07
If you're experiencing this, it's not caused by an issue with Mari0

**Comment by alesan99** [comment] 2024-05-28 18:24
Could possibly be fixed with the LOVE version upgrade.

Feel free to add more details about your Mari0 AE version and platform incase it still happens on the latest version

**Closed** 2024-08-09 20:21 UTC
Labels: bug
