### ISSUE TITLE
Player's Shrink and Grow Animations

### ISSUE THREAD

**Issue by LeanneTM** [alesan99/mari0_ae#71] opened 2021-05-06 20:04 UTC
idk if you may want to touch this (because when i tried, i failed cuz player code is too.. messy) but these animations in mari0 dont really match smb1 ones.

id suggest checking the thing frame by frame in a emulator to get them. :3

**Comment by WilliamFr0g** [comment] 2023-08-22 11:39
These aren't even really bad and the issue is years old, can we close it

**Closed** 2023-08-22 13:57 UTC
Labels: accuracy
